CREATE TABLE zzAchievementNew(
    RowId VARCHAR(36) PRIMARY KEY,
    DtCreation Timestamp NOT NULL,
    DtLastUpdate Timestamp NOT NULL,
    PlayerId VARCHAR(36) NOT NULL,
    AchievementType VARCHAR(255) NOT NULL,
    GameIdEarned VARCHAR(36) NOT NULL,
    AchievementCounter INT NOT NULL,
    AchievementDetail VARCHAR(255) NOT NULL,
    DtAchieved TIMESTAMP NOT NULL);

/**
ACHIEVEMENT_REF_X01_BEST_FINISH = 0
ACHIEVEMENT_REF_X01_BEST_THREE_DART_SCORE = 1
ACHIEVEMENT_REF_X01_CHECKOUT_COMPLETENESS = 2
ACHIEVEMENT_REF_X01_HIGHEST_BUST = 3
ACHIEVEMENT_REF_GOLF_POINTS_RISKED = 4
ACHIEVEMENT_REF_X01_GAMES_WON = 5
ACHIEVEMENT_REF_GOLF_GAMES_WON = 6
ACHIEVEMENT_REF_CLOCK_GAMES_WON = 7
ACHIEVEMENT_REF_X01_BEST_GAME = 8
ACHIEVEMENT_REF_GOLF_BEST_GAME = 9
ACHIEVEMENT_REF_CLOCK_BEST_GAME = 10
ACHIEVEMENT_REF_CLOCK_BRUCEY_BONUSES = 11
ACHIEVEMENT_REF_X01_SHANGHAI = 12
ACHIEVEMENT_REF_X01_HOTEL_INSPECTOR = 13
ACHIEVEMENT_REF_X01_SUCH_BAD_LUCK = 14
ACHIEVEMENT_REF_X01_BTBF = 15
ACHIEVEMENT_REF_CLOCK_BEST_STREAK = 16
ACHIEVEMENT_REF_X01_NO_MERCY = 17
ACHIEVEMENT_REF_GOLF_COURSE_MASTER = 18
ACHIEVEMENT_REF_DARTZEE_GAMES_WON = 19
 */

INSERT INTO zzAchievementNew
SELECT
    RowId,
    DtCreation,
    DtLastUpdate,
    PlayerId,
    CASE
        WHEN AchievementRef = 0 THEN 'X01_BEST_FINISH'
        WHEN AchievementRef = 1 THEN 'X01_BEST_THREE_DART_SCORE'
        WHEN AchievementRef = 2 THEN 'X01_CHECKOUT_COMPLETENESS'
        WHEN AchievementRef = 3 THEN 'X01_HIGHEST_BUST'
        WHEN AchievementRef = 4 THEN 'GOLF_POINTS_RISKED'
        WHEN AchievementRef = 5 THEN 'X01_GAMES_WON'
        WHEN AchievementRef = 6 THEN 'GOLF_GAMES_WON'
        WHEN AchievementRef = 7 THEN 'CLOCK_GAMES_WON'
        WHEN AchievementRef = 8 THEN 'X01_BEST_GAME'
        WHEN AchievementRef = 9 THEN 'GOLF_BEST_GAME'
        WHEN AchievementRef = 10 THEN 'CLOCK_BEST_GAME'
        WHEN AchievementRef = 11 THEN 'CLOCK_BRUCEY_BONUSES'
        WHEN AchievementRef = 12 THEN 'X01_SHANGHAI'
        WHEN AchievementRef = 13 THEN 'X01_HOTEL_INSPECTOR'
        WHEN AchievementRef = 14 THEN 'X01_SUCH_BAD_LUCK'
        WHEN AchievementRef = 15 THEN 'X01_BTBF'
        WHEN AchievementRef = 16 THEN 'CLOCK_BEST_STREAK'
        WHEN AchievementRef = 17 THEN 'X01_NO_MERCY'
        WHEN AchievementRef = 18 THEN 'GOLF_COURSE_MASTER'
        WHEN AchievementRef = 19 THEN 'DARTZEE_GAMES_WON'
        ELSE ''
    END,
    GameIdEarned,
    AchievementCounter,
    AchievementDetail,
    DtLastUpdate
FROM Achievement;

CREATE INDEX PlayerId_AchievemenType ON zzAchievementNew(PlayerId, AchievementType);

RENAME TABLE Achievement TO zzAchievementOld;
RENAME TABLE zzAchievementNew TO Achievement;
DROP TABLE zzAchievementOld