@file:JvmName("AchievementConstants")
package burlton.dartzee.code.achievements

/**
 * Constants for the darts achievements
 */
const val ACHIEVEMENT_REF_X01_BEST_FINISH = 0
const val ACHIEVEMENT_REF_X01_BEST_THREE_DART_SCORE = 1
const val ACHIEVEMENT_REF_X01_CHECKOUT_COMPLETENESS = 2
const val ACHIEVEMENT_REF_X01_HIGHEST_BUST = 3
const val ACHIEVEMENT_REF_GOLF_POINTS_RISKED = 4
const val ACHIEVEMENT_REF_X01_GAMES_WON = 5
const val ACHIEVEMENT_REF_GOLF_GAMES_WON = 6
const val ACHIEVEMENT_REF_CLOCK_GAMES_WON = 7
const val ACHIEVEMENT_REF_X01_BEST_GAME = 8
const val ACHIEVEMENT_REF_GOLF_BEST_GAME = 9
const val ACHIEVEMENT_REF_CLOCK_BEST_GAME = 10
const val ACHIEVEMENT_REF_CLOCK_BRUCEY_BONUSES = 11
const val ACHIEVEMENT_REF_X01_SHANGHAI = 12