package dartzee.utils

import dartzee.utils.DartsColour.DARTBOARD_BLACK_STR
import dartzee.utils.DartsColour.DARTBOARD_GREEN_STR
import dartzee.utils.DartsColour.DARTBOARD_RED_STR
import dartzee.utils.DartsColour.DARTBOARD_WHITE_STR

// Node names
const val NODE_PREFERENCES = "DartsPrefs"

// Variable names
val PREFERENCES_STRING_ODD_SINGLE_COLOUR = "oddsing;$DARTBOARD_WHITE_STR"
val PREFERENCES_STRING_ODD_DOUBLE_COLOUR = "odddoub;$DARTBOARD_GREEN_STR"
val PREFERENCES_STRING_ODD_TREBLE_COLOUR = "oddtreb;$DARTBOARD_GREEN_STR"
val PREFERENCES_STRING_EVEN_SINGLE_COLOUR = "evensing;$DARTBOARD_BLACK_STR"
val PREFERENCES_STRING_EVEN_DOUBLE_COLOUR = "evendoub;$DARTBOARD_RED_STR"
val PREFERENCES_STRING_EVEN_TREBLE_COLOUR = "eventreb;$DARTBOARD_RED_STR"
