package dartzee.achievements

enum class AchievementType
{
    X01_BEST_FINISH,
    X01_BEST_THREE_DART_SCORE,
    X01_CHECKOUT_COMPLETENESS,
    X01_HIGHEST_BUST,
    GOLF_POINTS_RISKED,
    X01_GAMES_WON,
    GOLF_GAMES_WON,
    CLOCK_GAMES_WON,
    X01_BEST_GAME,
    GOLF_BEST_GAME,
    CLOCK_BEST_GAME,
    CLOCK_BRUCEY_BONUSES,
    X01_SHANGHAI,
    X01_HOTEL_INSPECTOR,
    X01_SUCH_BAD_LUCK,
    X01_BTBF,
    CLOCK_BEST_STREAK,
    X01_NO_MERCY,
    GOLF_COURSE_MASTER,
    DARTZEE_GAMES_WON,
    DARTZEE_BEST_GAME,
    DARTZEE_FLAWLESS,
    DUMMY_TOTAL
}